Concat_PrimesDanteD'Onofrio,TessaHartmann: src/concat_primes.cpp File Reference
concat_primes.cpp File Reference
string manipulation using .substr
#include <iostream>
#include <assert.h>
#include <string>
Functions
std::string get_concatenated_primes ()
Function to count all prime numbers 0-1000.
std::string get_slice_of_5 (const std::string &primes, const int index)
Function to take section of prime numbers.
int main (int argc, char *argv[])
main function used for testing and prompt
Detailed Description
string manipulation using .substr
main tests the program before output of initial prompt, then asks for integer n program then runs function get_concatenated_primes, which calculates all prime numbers between 0 - 1000 and returns the accumulated object of strings then program runs get_slice_of_5 which takes the index and a length of five and returns just the subsection to main before output of the final five digits and prompts for more input
Requires: C++11
Function Documentation
std:: string get_concatenated_primes ()
Function to count all prime numbers 0-1000.
get_concatenated_primes:
First for loop itterates from 2 to 2000 by 1 each time and second for loop does the same. Boolean true and false used to test the value for prime or not prime. if i % j == 0 || i == j makes sure the number is not prime then if prime == true and i is not 1, number is prime. accumulation made simple by use of substr and to_string command. then the function returns accumulated substr to main.
Returns
std::string concat_primes.substr(0,1000)
Referenced by main().
std:: string get_slice_of_5 (const std::string & primes, const int index)
Function to take section of prime numbers.
get_slice_of_5:
The second function uses the concept and string function called substr, ie. substring. "Get slice of 5" as it is named will aid in returning the 5 digits. These 5 digits begin at the user entered index ("Please enter n = ") and will end after the 5th digit from that given index. This is done using the parameters (index, 5) in "ret = primes.sub str(index, 5);". Ret is then returned to print those 5 digits.
Returns
std::string ret
Referenced by main().
int main (int argc, char * argv[])
main function used for testing and prompt
main:
added tests 3-5 to main as outlined in project details.
Returns
0
References get_concatenated_primes(), and get_slice_of_5().